# Generated by Django 5.0.7 on 2024-08-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/%H/%M/%S/')),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('motherLanguage', models.CharField(max_length=50)),
                ('secoundLanguage', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('about', models.TextField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
