# Generated by Django 5.0.7 on 2024-08-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d/%H/%M/%S/', verbose_name='Profile Picture')),
                ('birthdate', models.DateField(verbose_name='Birth Date')),
                ('jopTitle', models.CharField(max_length=50, verbose_name='Jop Title')),
                ('email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('about', models.TextField(verbose_name='About me')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
