# Generated by Django 5.0.7 on 2024-08-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_account_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cardBackground',
            field=models.ImageField(default='static/assets/defaultBackGround/defaultBackGround.jpg', upload_to='images/logo/%Y/%m/%d/%H/%M/%S/', verbose_name='Card Background'),
        ),
    ]
