# Generated by Django 5.0.7 on 2024-08-11 21:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_account_cardbackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name='About me'),
        ),
    ]
