# Generated by Django 5.0.7 on 2024-08-12 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_account_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Software Programming Skills', 'Software Programming Skills'), (' Operating Systems', ' Operating Systems'), ('Editors', 'Editors'), ('IDEs', 'IDEs'), ('Design', 'Design')], default='Software Programming Skills', max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.account')),
            ],
        ),
    ]
