# Generated by Django 5.0.7 on 2024-08-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_remove_skills_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
