# Generated by Django 5.0.7 on 2024-08-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='honorsAndAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.account')),
            ],
            options={
                'verbose_name': 'Honor and Award',
                'verbose_name_plural': 'Honors and Awards',
            },
        ),
    ]
