# Generated by Django 5.0.7 on 2024-08-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_honorsandawards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honorsandawards',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='honorsAndAwards',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
    ]
