# Generated by Django 5.0.7 on 2024-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_competations'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pdfCV',
            field=models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d/%H/%M/%S/', verbose_name='PDF CV'),
        ),
    ]
