# Generated by Django 5.0.7 on 2024-08-14 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_alter_account_pdfcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pdfCV',
            field=models.FileField(upload_to='pdf/%Y/%m/%d/%H/%M/%S/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF CV'),
        ),
    ]
